# Generated by Django 5.1.2 on 2024-10-16 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_notification_notification_type_notification_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Like'), ('delete', 'Delete'), ('pending', 'Pending')], default='Like', max_length=10),
        ),
    ]
