# Generated by Django 5.1.2 on 2024-10-16 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Like'), ('delete', 'Delete'), ('pending', 'Pending'), ('approved', 'Approved')], default='Like', max_length=10),
        ),
    ]
