# Generated by Django 5.1.2 on 2024-10-18 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contactus',
        ),
    ]
